services:
  - type: web
    name: rs-global-ventures
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    autoDeploy: true
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
